CREATE TABLE IF NOT EXISTS animal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS car (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS gov_employee (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
); 